// Auto-generated from the Flutter app's Dart data. Do not edit by hand.
// Source: party/lib/data/word_lists.dart + generic_word_pool.dart

export const headsUpCategories = [
  {
    "name": "Movies & TV",
    "emoji": "🎬",
    "primary": "#E50914",
    "secondary": "#831010",
    "words": [
      "Star Wars",
      "Marvel (MCU)",
      "DC (Batman/Superman)",
      "Spider-Man",
      "Harry Potter",
      "Lord of the Rings",
      "The Hobbit",
      "Jurassic Park",
      "Fast & Furious",
      "Mission: Impossible",
      "James Bond",
      "Pirates of the Caribbean",
      "Transformers",
      "Toy Story",
      "Shrek",
      "Despicable Me / Minions",
      "Kung Fu Panda",
      "How to Train Your Dragon",
      "The Hunger Games",
      "Twilight",
      "John Wick",
      "Indiana Jones",
      "Back to the Future",
      "The Matrix",
      "Terminator",
      "Rocky",
      "Top Gun",
      "Scream",
      "The Conjuring",
      "Halloween",
      "Star Trek",
      "Planet of the Apes",
      "The Lego Movie",
      "Titanic",
      "Avatar",
      "Inception",
      "Interstellar",
      "Oppenheimer",
      "Barbie",
      "Dune",
      "Forrest Gump",
      "The Godfather",
      "The Shawshank Redemption",
      "Pulp Fiction",
      "Fight Club",
      "Goodfellas",
      "The Departed",
      "Gladiator",
      "Saving Private Ryan",
      "The Green Mile",
      "Cast Away",
      "Jaws",
      "E.T.",
      "The Lion King",
      "Aladdin",
      "Beauty and the Beast",
      "Frozen",
      "Moana",
      "Encanto",
      "Coco",
      "Finding Nemo",
      "Up",
      "Inside Out",
      "Monsters, Inc.",
      "The Incredibles",
      "Ratatouille",
      "WALL-E",
      "Mean Girls",
      "Legally Blonde",
      "Clueless",
      "The Hangover",
      "Superbad",
      "Step Brothers",
      "The Notebook",
      "La La Land",
      "The Greatest Showman",
      "Knives Out",
      "Parasite",
      "Everything Everywhere All at Once",
      "The Truman Show",
      "The Sixth Sense",
      "The Prestige",
      "The Martian",
      "Gravity",
      "Mad Max: Fury Road",
      "Alien",
      "Predator",
      "The Silence of the Lambs",
      "Ocean's Eleven",
      "Get Out",
      "A Quiet Place",
      "The Shining",
      "The Exorcist",
      "Friends",
      "The Office",
      "Breaking Bad",
      "Stranger Things",
      "Game of Thrones",
      "House of the Dragon",
      "The Walking Dead",
      "The Last of Us",
      "The Mandalorian",
      "The Boys",
      "The Witcher",
      "Wednesday",
      "Squid Game",
      "Black Mirror",
      "Sherlock",
      "Peaky Blinders",
      "Grey's Anatomy",
      "Euphoria",
      "The Big Bang Theory",
      "Seinfeld",
      "The Simpsons",
      "Family Guy",
      "South Park",
      "SpongeBob SquarePants",
      "Rick and Morty",
      "Avatar: The Last Airbender",
      "Suits",
      "Ted Lasso",
      "Succession",
      "The Good Place",
      "Cobra Kai",
      "The Umbrella Academy"
    ]
  },
  {
    "name": "Video Games",
    "emoji": "🎮",
    "primary": "#673AB7",
    "secondary": "#4527A0",
    "words": [
      "Minecraft",
      "Fortnite",
      "Roblox",
      "Among Us",
      "Valorant",
      "League of Legends",
      "Overwatch",
      "Apex Legends",
      "Call of Duty",
      "GTA",
      "Red Dead Redemption",
      "Mario Kart",
      "Super Smash Bros",
      "Zelda",
      "Pokemon",
      "Animal Crossing",
      "Stardew Valley",
      "Terraria",
      "Elden Ring",
      "Dark Souls",
      "Skyrim",
      "Fall Guys",
      "Rocket League",
      "FIFA",
      "NBA 2K",
      "Counter-Strike",
      "Team Fortress 2",
      "PUBG",
      "Rainbow Six Siege",
      "Genshin Impact",
      "Honkai: Star Rail",
      "Hades",
      "Hollow Knight",
      "Undertale",
      "Cuphead",
      "Portal",
      "Portal 2",
      "The Sims",
      "Five Nights at Freddy's",
      "Phasmophobia",
      "Subnautica",
      "Sea of Thieves",
      "God of War",
      "Spider-Man (PS)",
      "The Last of Us",
      "Cyberpunk 2077",
      "Geometry Dash",
      "Clash Royale",
      "Clash of Clans",
      "Brawl Stars",
      "Candy Crush",
      "Angry Birds",
      "Plants vs Zombies",
      "Tetris",
      "Wordle",
      "Osu!",
      "Beat Saber"
    ]
  },
  {
    "name": "Music (Artist — Song)",
    "emoji": "🎵",
    "primary": "#1DB954",
    "secondary": "#0B5D1E",
    "words": [
      "Taylor Swift — Cruel Summer",
      "Billie Eilish — Birds of a Feather",
      "Sabrina Carpenter — Espresso",
      "Chappell Roan — Good Luck, Babe!",
      "Laufey — From The Start",
      "Olivia Rodrigo — vampire",
      "Ariana Grande — we can't be friends",
      "The Weeknd — Blinding Lights",
      "Dua Lipa — Houdini",
      "Doja Cat — Paint The Town Red",
      "Kendrick Lamar — Not Like Us",
      "SZA — Snooze",
      "Post Malone — Sunflower",
      "Harry Styles — As It Was",
      "Miley Cyrus — Flowers",
      "Tate McRae — greedy",
      "Lil Nas X — INDUSTRY BABY",
      "Benson Boone — Beautiful Things",
      "Hozier — Too Sweet",
      "Gracie Abrams — That's So True",
      "Shaboozey — A Bar Song (Tipsy)",
      "Morgan Wallen — Last Night",
      "The Kid LAROI — STAY",
      "Bad Bunny — Tití Me Preguntó",
      "Travis Scott — SICKO MODE",
      "Drake — God's Plan",
      "Justin Bieber — Peaches",
      "Rihanna — Diamonds",
      "Beyoncé — CUFF IT",
      "Lady Gaga — Bad Romance",
      "Bruno Mars — Locked Out of Heaven",
      "Ed Sheeran — Shape of You",
      "Adele — Rolling in the Deep",
      "Sam Smith — Stay With Me",
      "Lizzo — About Damn Time",
      "Karol G — PROVENZA",
      "Peso Pluma — Ella Baila Sola",
      "Ice Spice — Munch",
      "PinkPantheress — Boy's a liar",
      "Charlie Puth — Attention",
      "Camila Cabello — Havana",
      "Shawn Mendes — There's Nothing Holdin' Me Back",
      "Selena Gomez — Lose You to Love Me",
      "Halsey — Without Me",
      "Lana Del Rey — Summertime Sadness",
      "Frank Ocean — Lost",
      "Tyler, The Creator — SEE YOU AGAIN",
      "Joji — Glimpse of Us",
      "Keshi — LIMBO",
      "The Neighbourhood — Sweater Weather",
      "Arctic Monkeys — 505",
      "Imagine Dragons — Believer",
      "Coldplay — Viva La Vida",
      "OneRepublic — Counting Stars",
      "Yung Kai — Blue",
      "Queen — Bohemian Rhapsody",
      "The Beatles — Here Comes the Sun",
      "Michael Jackson — Billie Jean",
      "Elton John — Rocket Man",
      "ABBA — Dancing Queen",
      "Whitney Houston — I Will Always Love You",
      "Prince — Purple Rain",
      "Madonna — Like a Prayer",
      "Journey — Don't Stop Believin'",
      "Bon Jovi — Livin' on a Prayer",
      "U2 — With or Without You",
      "Fleetwood Mac — Dreams",
      "Eagles — Hotel California",
      "The Rolling Stones — Paint It Black",
      "Nirvana — Smells Like Teen Spirit",
      "Red Hot Chili Peppers — Californication",
      "Green Day — Boulevard of Broken Dreams",
      "Linkin Park — In the End",
      "Eminem — Lose Yourself",
      "Outkast — Hey Ya!",
      "Usher — Yeah!",
      "Kanye West — Stronger",
      "Rihanna — Umbrella",
      "Beyoncé — Single Ladies",
      "Lady Gaga — Poker Face",
      "Bruno Mars — Just the Way You Are",
      "Alicia Keys — No One",
      "Maroon 5 — Sugar",
      "The Black Eyed Peas — I Gotta Feeling",
      "Daft Punk — Get Lucky",
      "Avicii — Wake Me Up",
      "Calvin Harris — Summer"
    ]
  },
  {
    "name": "Animals",
    "emoji": "🦁",
    "primary": "#4CAF50",
    "secondary": "#2E7D32",
    "words": [
      "Elephant",
      "Giraffe",
      "Penguin",
      "Kangaroo",
      "Dolphin",
      "Tiger",
      "Gorilla",
      "Octopus",
      "Flamingo",
      "Koala",
      "Crocodile",
      "Peacock",
      "Rhinoceros",
      "Cheetah",
      "Panda",
      "Chameleon",
      "Hippopotamus",
      "Eagle",
      "Jellyfish",
      "Sloth",
      "Armadillo",
      "Platypus",
      "Zebra",
      "Lobster",
      "Parrot",
      "Hamster",
      "Squirrel",
      "Hedgehog",
      "Butterfly",
      "Seahorse",
      "Wolf",
      "Fox",
      "Bear",
      "Owl",
      "Shark",
      "Whale",
      "Frog",
      "Snake",
      "Turtle",
      "Bee"
    ]
  },
  {
    "name": "Food & Drinks",
    "emoji": "🍕",
    "primary": "#FF5722",
    "secondary": "#BF360C",
    "words": [
      "Pizza",
      "Burger",
      "Hot Dog",
      "Sandwich",
      "Grilled Cheese",
      "Mac and Cheese",
      "Fried Chicken",
      "Chicken Nuggets",
      "Steak",
      "Ribs",
      "Meatballs",
      "Spaghetti",
      "Pasta",
      "Noodles",
      "Rice",
      "Fried Rice",
      "Soup",
      "Chicken Soup",
      "Salad",
      "Caesar Salad",
      "French Fries",
      "Onion Rings",
      "Mashed Potatoes",
      "Baked Potato",
      "Pancakes",
      "Waffles",
      "French Toast",
      "Eggs",
      "Omelet",
      "Bacon",
      "Sausage",
      "Toast",
      "Bagel",
      "Cereal",
      "Oatmeal",
      "Yogurt",
      "Smoothie",
      "Chips",
      "Popcorn",
      "Pretzels",
      "Crackers",
      "Trail Mix",
      "Granola Bar",
      "Cheese Sticks",
      "Nachos",
      "Guacamole",
      "Hummus",
      "Spring Rolls",
      "Ice Cream",
      "Milkshake",
      "Chocolate",
      "Brownie",
      "Cupcake",
      "Cake",
      "Cookies",
      "Doughnut",
      "Cheesecake",
      "Apple Pie",
      "Candy",
      "Tacos",
      "Burrito",
      "Quesadilla",
      "Sushi",
      "Tempura",
      "Dumplings",
      "Ramen",
      "Hot Pot",
      "KBBQ",
      "Curry",
      "Falafel",
      "Pita",
      "Gyro",
      "Shawarma",
      "Fish and Chips",
      "Shepherd's Pie",
      "Paella",
      "Fried Plantains",
      "Empanadas",
      "Arepas",
      "Water",
      "Soda",
      "Cola",
      "Juice",
      "Orange Juice",
      "Lemonade",
      "Iced Tea",
      "Hot Tea",
      "Coffee",
      "Iced Coffee",
      "Latte",
      "Espresso",
      "Milk",
      "Chocolate Milk",
      "Protein Shake",
      "Boba",
      "Smoothie Bowl"
    ]
  },
  {
    "name": "Brands",
    "emoji": "🏷️",
    "primary": "#607D8B",
    "secondary": "#37474F",
    "words": [
      "Apple",
      "Google",
      "Microsoft",
      "Samsung",
      "Sony",
      "Intel",
      "AMD",
      "NVIDIA",
      "Meta",
      "Amazon",
      "Netflix",
      "YouTube",
      "TikTok",
      "Instagram",
      "Snapchat",
      "Spotify",
      "Discord",
      "Zoom",
      "PayPal",
      "Venmo",
      "PlayStation",
      "Xbox",
      "Nintendo",
      "Nintendo Switch",
      "Steam",
      "Epic Games",
      "Razer",
      "Logitech",
      "McDonald's",
      "Burger King",
      "Wendy's",
      "Subway",
      "KFC",
      "Chick-fil-A",
      "In-N-Out",
      "Taco Bell",
      "Chipotle",
      "Domino's",
      "Pizza Hut",
      "Starbucks",
      "Dunkin'",
      "Panda Express",
      "Popeyes",
      "Five Guys",
      "Nike",
      "Adidas",
      "Puma",
      "Under Armour",
      "Uniqlo",
      "Zara",
      "H&M",
      "Shein",
      "Levi's",
      "Lululemon",
      "Patagonia",
      "North Face",
      "Gucci",
      "Louis Vuitton",
      "Supreme",
      "Vans",
      "Converse",
      "Tesla",
      "Toyota",
      "Honda",
      "BMW",
      "Mercedes-Benz",
      "Audi",
      "Ford",
      "Chevrolet",
      "Hyundai",
      "Kia",
      "Uber",
      "Lyft",
      "Airbnb",
      "Target",
      "Walmart",
      "Costco",
      "IKEA",
      "Best Buy",
      "Home Depot",
      "Lowe's",
      "Trader Joe's",
      "Whole Foods",
      "CVS",
      "Walgreens",
      "Disney",
      "Pixar",
      "Marvel",
      "DC",
      "HBO",
      "Hulu",
      "Paramount",
      "Universal",
      "LEGO",
      "GoPro",
      "Dyson",
      "Fitbit",
      "Garmin",
      "Peloton",
      "Red Bull",
      "Monster",
      "Gatorade",
      "Air Jordan"
    ]
  },
  {
    "name": "Objects",
    "emoji": "📦",
    "primary": "#795548",
    "secondary": "#4E342E",
    "words": [
      "Phone",
      "Laptop",
      "Backpack",
      "Chair",
      "Table",
      "Mirror",
      "Clock",
      "Bottle",
      "Cup",
      "Notebook",
      "Pen",
      "Pencil",
      "Headphones",
      "TV",
      "Remote",
      "Keyboard",
      "Mouse",
      "Wallet",
      "Keys",
      "Charger",
      "Water Bottle",
      "Umbrella",
      "Sunglasses",
      "Camera",
      "Speaker",
      "Flashlight",
      "Blanket",
      "Pillow",
      "Book",
      "Sticky Notes",
      "Scissors",
      "Tape",
      "Glue",
      "Calculator",
      "Controller",
      "Microphone",
      "Mug",
      "Plate",
      "Fork",
      "Spoon",
      "Toothbrush",
      "Hairbrush",
      "Towel",
      "Fan",
      "ID Card",
      "AirPods",
      "Power Bank"
    ]
  },
  {
    "name": "Actions",
    "emoji": "🏃",
    "primary": "#9C27B0",
    "secondary": "#6A1B9A",
    "words": [
      "Dancing",
      "Singing",
      "Skating",
      "Surfing",
      "Skiing",
      "Snowboarding",
      "Running",
      "Jumping",
      "Climbing",
      "Swimming",
      "Flying",
      "Fighting",
      "Boxing",
      "Kicking",
      "Punching",
      "Throwing",
      "Catching",
      "Dodging",
      "Chasing",
      "Hiding",
      "Sneaking",
      "Crawling",
      "Marching",
      "Tiptoeing",
      "Skipping",
      "Spinning",
      "Balancing",
      "Stretching",
      "Posing",
      "Celebrating",
      "Cheering",
      "Panic running",
      "Faceplanting",
      "Slipping",
      "Falling",
      "Waving",
      "Clapping",
      "High-fiving",
      "Thumbs-upping",
      "Shrugging",
      "Nodding",
      "Facepalming",
      "Gasping",
      "Laughing",
      "Crying"
    ]
  },
  {
    "name": "Anime",
    "emoji": "🍥",
    "primary": "#FF7043",
    "secondary": "#D84315",
    "words": [
      "Naruto",
      "One Piece",
      "Dragon Ball",
      "Attack on Titan",
      "Demon Slayer",
      "Jujutsu Kaisen",
      "My Hero Academia",
      "Death Note",
      "Bleach",
      "Hunter x Hunter",
      "One Punch Man",
      "Chainsaw Man",
      "Tokyo Ghoul",
      "Haikyuu",
      "Blue Lock",
      "Spy x Family",
      "Fullmetal Alchemist",
      "JoJo",
      "Black Clover",
      "Fairy Tail",
      "Sword Art Online",
      "Pokemon",
      "Studio Ghibli",
      "Spirited Away",
      "Your Name",
      "Cowboy Bebop",
      "Evangelion",
      "Mob Psycho",
      "Solo Leveling",
      "Vinland Saga",
      "Dandadan",
      "Frieren",
      "Oshi no Ko",
      "Kaguya-sama",
      "The Promised Neverland",
      "Violet Evergarden",
      "Tokyo Revengers",
      "Re:Zero",
      "K-On!",
      "Horimiya"
    ]
  },
  {
    "name": "Jobs & Professions",
    "emoji": "💼",
    "primary": "#3F51B5",
    "secondary": "#283593",
    "words": [
      "Doctor",
      "Nurse",
      "Teacher",
      "Professor",
      "Engineer",
      "Programmer",
      "Data Scientist",
      "Designer",
      "Architect",
      "Chef",
      "Baker",
      "Waiter",
      "Cashier",
      "Barista",
      "Pilot",
      "Flight Attendant",
      "Police Officer",
      "Firefighter",
      "Detective",
      "Lawyer",
      "Judge",
      "Accountant",
      "Entrepreneur",
      "CEO",
      "Manager",
      "Mechanic",
      "Electrician",
      "Plumber",
      "Construction Worker",
      "Photographer",
      "Videographer",
      "Actor",
      "Director",
      "Musician",
      "Athlete",
      "Coach",
      "Scientist",
      "Researcher",
      "Journalist",
      "Therapist",
      "Pharmacist",
      "Dentist",
      "Veterinarian",
      "Librarian",
      "Real Estate Agent",
      "UX Designer",
      "Product Manager"
    ]
  },
  {
    "name": "School Subjects",
    "emoji": "📚",
    "primary": "#009688",
    "secondary": "#004D40",
    "words": [
      "Math",
      "Algebra",
      "Geometry",
      "Calculus",
      "Statistics",
      "Physics",
      "Chemistry",
      "Biology",
      "English",
      "Literature",
      "Writing",
      "World History",
      "US History",
      "Government",
      "Economics",
      "Geography",
      "Computer Science",
      "Programming",
      "Robotics",
      "Engineering",
      "Psychology",
      "Sociology",
      "Philosophy",
      "Art",
      "Music",
      "Drama",
      "Photography",
      "Journalism",
      "Debate",
      "Public Speaking",
      "Environmental Science",
      "Astronomy",
      "Marine Biology",
      "Anatomy",
      "Ethics",
      "Business",
      "Finance",
      "Language",
      "Spanish",
      "French",
      "Chinese",
      "Latin"
    ]
  },
  {
    "name": "Instruments",
    "emoji": "🎸",
    "primary": "#795548",
    "secondary": "#3E2723",
    "words": [
      "Piano",
      "Keyboard",
      "Guitar",
      "Electric Guitar",
      "Bass",
      "Drums",
      "Violin",
      "Viola",
      "Cello",
      "Double Bass",
      "Flute",
      "Clarinet",
      "Oboe",
      "Saxophone",
      "Trumpet",
      "Trombone",
      "French Horn",
      "Tuba",
      "Harp",
      "Ukulele",
      "Banjo",
      "Mandolin",
      "Accordion",
      "Harmonica",
      "Xylophone",
      "Marimba",
      "Synthesizer",
      "DJ Controller",
      "Turntable",
      "Kalimba",
      "Tambourine",
      "Triangle",
      "Conga",
      "Bongo",
      "Cajón",
      "Recorder"
    ]
  },
  {
    "name": "Landmarks",
    "emoji": "🏛️",
    "primary": "#8D6E63",
    "secondary": "#5D4037",
    "words": [
      "Eiffel Tower",
      "Statue of Liberty",
      "Golden Gate Bridge",
      "Big Ben",
      "Colosseum",
      "Great Wall of China",
      "Pyramids of Giza",
      "Taj Mahal",
      "Mount Everest",
      "Niagara Falls",
      "Grand Canyon",
      "Times Square",
      "Hollywood Sign",
      "Sydney Opera House",
      "Burj Khalifa",
      "Stonehenge",
      "Machu Picchu",
      "Christ the Redeemer",
      "Mount Fuji",
      "Sagrada Familia",
      "Louvre Museum",
      "Empire State Building",
      "CN Tower",
      "Space Needle",
      "White House",
      "Buckingham Palace",
      "Petra",
      "Angkor Wat",
      "Acropolis",
      "Brandenburg Gate"
    ]
  },
  {
    "name": "Everything",
    "emoji": "🌈",
    "primary": "#9E9E9E",
    "secondary": "#424242",
    "words": [
      "Star Wars",
      "Marvel (MCU)",
      "DC (Batman/Superman)",
      "Spider-Man",
      "Harry Potter",
      "Lord of the Rings",
      "The Hobbit",
      "Jurassic Park",
      "Fast & Furious",
      "Mission: Impossible",
      "James Bond",
      "Pirates of the Caribbean",
      "Transformers",
      "Toy Story",
      "Shrek",
      "Despicable Me / Minions",
      "Kung Fu Panda",
      "How to Train Your Dragon",
      "The Hunger Games",
      "Twilight",
      "John Wick",
      "Indiana Jones",
      "Back to the Future",
      "The Matrix",
      "Terminator",
      "Rocky",
      "Top Gun",
      "Scream",
      "The Conjuring",
      "Halloween",
      "Star Trek",
      "Planet of the Apes",
      "The Lego Movie",
      "Titanic",
      "Avatar",
      "Inception",
      "Interstellar",
      "Oppenheimer",
      "Barbie",
      "Dune",
      "Forrest Gump",
      "The Godfather",
      "The Shawshank Redemption",
      "Pulp Fiction",
      "Fight Club",
      "Goodfellas",
      "The Departed",
      "Gladiator",
      "Saving Private Ryan",
      "The Green Mile",
      "Cast Away",
      "Jaws",
      "E.T.",
      "The Lion King",
      "Aladdin",
      "Beauty and the Beast",
      "Frozen",
      "Moana",
      "Encanto",
      "Coco",
      "Finding Nemo",
      "Up",
      "Inside Out",
      "Monsters, Inc.",
      "The Incredibles",
      "Ratatouille",
      "WALL-E",
      "Mean Girls",
      "Legally Blonde",
      "Clueless",
      "The Hangover",
      "Superbad",
      "Step Brothers",
      "The Notebook",
      "La La Land",
      "The Greatest Showman",
      "Knives Out",
      "Parasite",
      "Everything Everywhere All at Once",
      "The Truman Show",
      "The Sixth Sense",
      "The Prestige",
      "The Martian",
      "Gravity",
      "Mad Max: Fury Road",
      "Alien",
      "Predator",
      "The Silence of the Lambs",
      "Ocean's Eleven",
      "Get Out",
      "A Quiet Place",
      "The Shining",
      "The Exorcist",
      "Friends",
      "The Office",
      "Breaking Bad",
      "Stranger Things",
      "Game of Thrones",
      "House of the Dragon",
      "The Walking Dead",
      "The Last of Us",
      "The Mandalorian",
      "The Boys",
      "The Witcher",
      "Wednesday",
      "Squid Game",
      "Black Mirror",
      "Sherlock",
      "Peaky Blinders",
      "Money Heist",
      "The Crown",
      "Grey's Anatomy",
      "Euphoria",
      "Gossip Girl",
      "How I Met Your Mother",
      "Modern Family",
      "Brooklyn Nine-Nine",
      "Parks and Recreation",
      "The Big Bang Theory",
      "Seinfeld",
      "The Simpsons",
      "Family Guy",
      "South Park",
      "SpongeBob SquarePants",
      "Rick and Morty",
      "Avatar: The Last Airbender",
      "Suits",
      "The Bear",
      "Ted Lasso",
      "Succession",
      "The Good Place",
      "Cobra Kai",
      "The Umbrella Academy",
      "Minecraft",
      "Fortnite",
      "Roblox",
      "Among Us",
      "Valorant",
      "League of Legends",
      "Overwatch",
      "Apex Legends",
      "Call of Duty",
      "GTA",
      "Red Dead Redemption",
      "Mario Kart",
      "Super Smash Bros",
      "Zelda",
      "Pokemon",
      "Animal Crossing",
      "Stardew Valley",
      "Terraria",
      "Elden Ring",
      "Dark Souls",
      "Skyrim",
      "Fall Guys",
      "Rocket League",
      "FIFA",
      "NBA 2K",
      "Counter-Strike",
      "Team Fortress 2",
      "PUBG",
      "Rainbow Six Siege",
      "Genshin Impact",
      "Honkai: Star Rail",
      "Hades",
      "Hollow Knight",
      "Undertale",
      "Cuphead",
      "Portal",
      "Portal 2",
      "The Sims",
      "Five Nights at Freddy's",
      "Phasmophobia",
      "Subnautica",
      "Sea of Thieves",
      "God of War",
      "Spider-Man (PS)",
      "The Last of Us",
      "Cyberpunk 2077",
      "Geometry Dash",
      "Clash Royale",
      "Clash of Clans",
      "Brawl Stars",
      "Candy Crush",
      "Angry Birds",
      "Plants vs Zombies",
      "Tetris",
      "Wordle",
      "Osu!",
      "Beat Saber",
      "Taylor Swift — Cruel Summer",
      "Billie Eilish — Birds of a Feather",
      "Sabrina Carpenter — Espresso",
      "Chappell Roan — Good Luck, Babe!",
      "Laufey — From The Start",
      "Olivia Rodrigo — vampire",
      "Ariana Grande — we can't be friends",
      "The Weeknd — Blinding Lights",
      "Dua Lipa — Houdini",
      "Doja Cat — Paint The Town Red",
      "Kendrick Lamar — Not Like Us",
      "SZA — Snooze",
      "Post Malone — Sunflower",
      "Harry Styles — As It Was",
      "Miley Cyrus — Flowers",
      "Tate McRae — greedy",
      "Lil Nas X — INDUSTRY BABY",
      "Benson Boone — Beautiful Things",
      "Hozier — Too Sweet",
      "Gracie Abrams — That's So True",
      "Shaboozey — A Bar Song (Tipsy)",
      "Morgan Wallen — Last Night",
      "The Kid LAROI — STAY",
      "Bad Bunny — Tití Me Preguntó",
      "Travis Scott — SICKO MODE",
      "Drake — God's Plan",
      "Justin Bieber — Peaches",
      "Rihanna — Diamonds",
      "Beyoncé — CUFF IT",
      "Lady Gaga — Bad Romance",
      "Bruno Mars — Locked Out of Heaven",
      "Ed Sheeran — Shape of You",
      "Adele — Rolling in the Deep",
      "Sam Smith — Stay With Me",
      "Lizzo — About Damn Time",
      "Karol G — PROVENZA",
      "Peso Pluma — Ella Baila Sola",
      "Ice Spice — Munch",
      "PinkPantheress — Boy's a liar",
      "Charlie Puth — Attention",
      "Camila Cabello — Havana",
      "Shawn Mendes — There's Nothing Holdin' Me Back",
      "Selena Gomez — Lose You to Love Me",
      "Halsey — Without Me",
      "Lana Del Rey — Summertime Sadness",
      "Frank Ocean — Lost",
      "Tyler, The Creator — SEE YOU AGAIN",
      "Joji — Glimpse of Us",
      "Keshi — LIMBO",
      "The Neighbourhood — Sweater Weather",
      "Arctic Monkeys — 505",
      "Imagine Dragons — Believer",
      "Coldplay — Viva La Vida",
      "OneRepublic — Counting Stars",
      "Yung Kai — Blue",
      "Queen — Bohemian Rhapsody",
      "The Beatles — Here Comes the Sun",
      "Michael Jackson — Billie Jean",
      "Elton John — Rocket Man",
      "ABBA — Dancing Queen",
      "Whitney Houston — I Will Always Love You",
      "Prince — Purple Rain",
      "Madonna — Like a Prayer",
      "Journey — Don't Stop Believin'",
      "Bon Jovi — Livin' on a Prayer",
      "U2 — With or Without You",
      "Fleetwood Mac — Dreams",
      "Eagles — Hotel California",
      "The Rolling Stones — Paint It Black",
      "Nirvana — Smells Like Teen Spirit",
      "Red Hot Chili Peppers — Californication",
      "Green Day — Boulevard of Broken Dreams",
      "Linkin Park — In the End",
      "Eminem — Lose Yourself",
      "Outkast — Hey Ya!",
      "Usher — Yeah!",
      "Kanye West — Stronger",
      "Rihanna — Umbrella",
      "Beyoncé — Single Ladies",
      "Lady Gaga — Poker Face",
      "Bruno Mars — Just the Way You Are",
      "Alicia Keys — No One",
      "Maroon 5 — Sugar",
      "The Black Eyed Peas — I Gotta Feeling",
      "Daft Punk — Get Lucky",
      "Avicii — Wake Me Up",
      "Calvin Harris — Summer",
      "Elephant",
      "Giraffe",
      "Penguin",
      "Kangaroo",
      "Dolphin",
      "Tiger",
      "Gorilla",
      "Octopus",
      "Flamingo",
      "Koala",
      "Crocodile",
      "Peacock",
      "Rhinoceros",
      "Cheetah",
      "Panda",
      "Chameleon",
      "Hippopotamus",
      "Eagle",
      "Jellyfish",
      "Sloth",
      "Armadillo",
      "Platypus",
      "Zebra",
      "Lobster",
      "Parrot",
      "Hamster",
      "Squirrel",
      "Hedgehog",
      "Butterfly",
      "Seahorse",
      "Wolf",
      "Fox",
      "Bear",
      "Owl",
      "Shark",
      "Whale",
      "Frog",
      "Snake",
      "Turtle",
      "Bee",
      "Pizza",
      "Burger",
      "Hot Dog",
      "Sandwich",
      "Grilled Cheese",
      "Mac and Cheese",
      "Fried Chicken",
      "Chicken Nuggets",
      "Steak",
      "Ribs",
      "Meatballs",
      "Spaghetti",
      "Pasta",
      "Noodles",
      "Rice",
      "Fried Rice",
      "Soup",
      "Chicken Soup",
      "Salad",
      "Caesar Salad",
      "French Fries",
      "Onion Rings",
      "Mashed Potatoes",
      "Baked Potato",
      "Pancakes",
      "Waffles",
      "French Toast",
      "Eggs",
      "Omelet",
      "Bacon",
      "Sausage",
      "Toast",
      "Bagel",
      "Cereal",
      "Oatmeal",
      "Yogurt",
      "Smoothie",
      "Chips",
      "Popcorn",
      "Pretzels",
      "Crackers",
      "Trail Mix",
      "Granola Bar",
      "Cheese Sticks",
      "Nachos",
      "Guacamole",
      "Hummus",
      "Spring Rolls",
      "Ice Cream",
      "Milkshake",
      "Chocolate",
      "Brownie",
      "Cupcake",
      "Cake",
      "Cookies",
      "Doughnut",
      "Cheesecake",
      "Apple Pie",
      "Candy",
      "Tacos",
      "Burrito",
      "Quesadilla",
      "Sushi",
      "Tempura",
      "Dumplings",
      "Ramen",
      "Hot Pot",
      "KBBQ",
      "Curry",
      "Falafel",
      "Pita",
      "Gyro",
      "Shawarma",
      "Fish and Chips",
      "Shepherd's Pie",
      "Paella",
      "Fried Plantains",
      "Empanadas",
      "Arepas",
      "Water",
      "Soda",
      "Cola",
      "Juice",
      "Orange Juice",
      "Lemonade",
      "Iced Tea",
      "Hot Tea",
      "Coffee",
      "Iced Coffee",
      "Latte",
      "Espresso",
      "Milk",
      "Chocolate Milk",
      "Protein Shake",
      "Boba",
      "Smoothie Bowl",
      "Apple",
      "Google",
      "Microsoft",
      "Samsung",
      "Sony",
      "Intel",
      "AMD",
      "NVIDIA",
      "Meta",
      "Amazon",
      "Netflix",
      "YouTube",
      "TikTok",
      "Instagram",
      "Snapchat",
      "Spotify",
      "Discord",
      "Zoom",
      "PayPal",
      "Venmo",
      "PlayStation",
      "Xbox",
      "Nintendo",
      "Nintendo Switch",
      "Steam",
      "Epic Games",
      "Razer",
      "Logitech",
      "McDonald's",
      "Burger King",
      "Wendy's",
      "Subway",
      "KFC",
      "Chick-fil-A",
      "In-N-Out",
      "Taco Bell",
      "Chipotle",
      "Domino's",
      "Pizza Hut",
      "Starbucks",
      "Dunkin'",
      "Panda Express",
      "Popeyes",
      "Five Guys",
      "Nike",
      "Adidas",
      "Puma",
      "Under Armour",
      "Uniqlo",
      "Zara",
      "H&M",
      "Shein",
      "Levi's",
      "Lululemon",
      "Patagonia",
      "North Face",
      "Gucci",
      "Louis Vuitton",
      "Supreme",
      "Vans",
      "Converse",
      "Tesla",
      "Toyota",
      "Honda",
      "BMW",
      "Mercedes-Benz",
      "Audi",
      "Ford",
      "Chevrolet",
      "Hyundai",
      "Kia",
      "Uber",
      "Lyft",
      "Airbnb",
      "Target",
      "Walmart",
      "Costco",
      "IKEA",
      "Best Buy",
      "Home Depot",
      "Lowe's",
      "Trader Joe's",
      "Whole Foods",
      "CVS",
      "Walgreens",
      "Disney",
      "Pixar",
      "Marvel",
      "DC",
      "HBO",
      "Hulu",
      "Paramount",
      "Universal",
      "LEGO",
      "GoPro",
      "Dyson",
      "Fitbit",
      "Garmin",
      "Peloton",
      "Red Bull",
      "Monster",
      "Gatorade",
      "Air Jordan",
      "Phone",
      "Laptop",
      "Backpack",
      "Chair",
      "Table",
      "Mirror",
      "Clock",
      "Bottle",
      "Cup",
      "Notebook",
      "Pen",
      "Pencil",
      "Headphones",
      "TV",
      "Remote",
      "Keyboard",
      "Mouse",
      "Wallet",
      "Keys",
      "Charger",
      "Water Bottle",
      "Umbrella",
      "Sunglasses",
      "Camera",
      "Speaker",
      "Flashlight",
      "Blanket",
      "Pillow",
      "Book",
      "Sticky Notes",
      "Scissors",
      "Tape",
      "Glue",
      "Calculator",
      "Controller",
      "Microphone",
      "Mug",
      "Plate",
      "Fork",
      "Spoon",
      "Toothbrush",
      "Hairbrush",
      "Towel",
      "Fan",
      "ID Card",
      "AirPods",
      "Power Bank",
      "Dancing",
      "Sleeping",
      "Laughing",
      "Crying",
      "Jumping",
      "Running",
      "Swimming",
      "Flying",
      "Singing",
      "Cooking",
      "Driving",
      "Reading",
      "Writing",
      "Drawing",
      "Climbing",
      "Sneezing",
      "Yawning",
      "Stretching",
      "Waving",
      "Clapping",
      "Whistling",
      "Juggling",
      "Tiptoeing",
      "Skipping",
      "Crawling",
      "Hugging",
      "Kissing",
      "Whispering",
      "Shouting",
      "Meditating",
      "Texting",
      "Calling",
      "High-fiving",
      "Thumbs up",
      "Facepalming",
      "Nodding",
      "Shrugging",
      "Winking",
      "Cheering",
      "Fist bumping",
      "Dabbing",
      "Rapping",
      "Beatboxing",
      "Snapping",
      "Gasping",
      "Screaming",
      "Naruto",
      "One Piece",
      "Dragon Ball",
      "Attack on Titan",
      "Demon Slayer",
      "Jujutsu Kaisen",
      "My Hero Academia",
      "Death Note",
      "Bleach",
      "Hunter x Hunter",
      "One Punch Man",
      "Chainsaw Man",
      "Tokyo Ghoul",
      "Haikyuu",
      "Blue Lock",
      "Spy x Family",
      "Fullmetal Alchemist",
      "JoJo",
      "Black Clover",
      "Fairy Tail",
      "Sword Art Online",
      "Pokemon",
      "Studio Ghibli",
      "Spirited Away",
      "Your Name",
      "Cowboy Bebop",
      "Evangelion",
      "Mob Psycho",
      "Solo Leveling",
      "Vinland Saga",
      "Dandadan",
      "Frieren",
      "Oshi no Ko",
      "Kaguya-sama",
      "The Promised Neverland",
      "Violet Evergarden",
      "Tokyo Revengers",
      "Re:Zero",
      "K-On!",
      "Horimiya"
    ]
  }
];

export const genericWordPool = [
  "absent",
  "absorb",
  "abuse",
  "access",
  "accident",
  "account",
  "accuse",
  "achieve",
  "acid",
  "acoustic",
  "acquire",
  "act",
  "action",
  "active",
  "actor",
  "adapt",
  "add",
  "address",
  "adjust",
  "adult",
  "advance",
  "advice",
  "affair",
  "afford",
  "afraid",
  "age",
  "agent",
  "agree",
  "ahead",
  "aim",
  "air",
  "airport",
  "aisle",
  "alarm",
  "album",
  "alcohol",
  "alert",
  "alien",
  "allow",
  "alone",
  "alter",
  "amateur",
  "amazing",
  "amount",
  "anchor",
  "ancient",
  "anger",
  "angle",
  "angry",
  "animal",
  "ankle",
  "announce",
  "annual",
  "answer",
  "antenna",
  "antique",
  "anxiety",
  "apology",
  "appear",
  "apple",
  "apply",
  "april",
  "area",
  "arena",
  "argue",
  "arm",
  "armed",
  "army",
  "arrange",
  "arrest",
  "arrive",
  "arrow",
  "art",
  "article",
  "artist",
  "ask",
  "aspect",
  "assault",
  "asset",
  "assist",
  "assume",
  "asthma",
  "athlete",
  "atom",
  "attack",
  "attempt",
  "attend",
  "attention",
  "attitude",
  "attorney",
  "attract",
  "auction",
  "august",
  "aunt",
  "author",
  "auto",
  "autumn",
  "average",
  "avocado",
  "avoid",
  "awake",
  "award",
  "aware",
  "awesome",
  "awful",
  "awkward",
  "axis",
  "baby",
  "bachelor",
  "bacon",
  "badge",
  "bag",
  "balance",
  "ball",
  "bamboo",
  "banana",
  "banner",
  "bar",
  "bargain",
  "barrel",
  "base",
  "basic",
  "basket",
  "battle",
  "beach",
  "bean",
  "bear",
  "beauty",
  "become",
  "bed",
  "beef",
  "begin",
  "behave",
  "belief",
  "bell",
  "belt",
  "bench",
  "benefit",
  "best",
  "betray",
  "better",
  "bicycle",
  "bid",
  "bike",
  "bill",
  "bind",
  "biology",
  "bird",
  "birth",
  "bitter",
  "black",
  "blade",
  "blame",
  "blanket",
  "blast",
  "bless",
  "blind",
  "block",
  "blood",
  "blossom",
  "blow",
  "blue",
  "board",
  "boat",
  "body",
  "boil",
  "bold",
  "bolt",
  "bomb",
  "bond",
  "bone",
  "bonus",
  "book",
  "boost",
  "border",
  "boring",
  "borrow",
  "boss",
  "bottle",
  "bottom",
  "boundary",
  "bowl",
  "brain",
  "branch",
  "brand",
  "brass",
  "brave",
  "bread",
  "break",
  "breeze",
  "brick",
  "bridge",
  "brief",
  "bright",
  "bring",
  "broad",
  "broken",
  "brother",
  "brown",
  "brush",
  "bubble",
  "bucket",
  "budget",
  "build",
  "bulb",
  "bulk",
  "bump",
  "bunch",
  "bundle",
  "burden",
  "burn",
  "burst",
  "bus",
  "bush",
  "business",
  "butter",
  "button",
  "buy",
  "cabbage",
  "cable",
  "cage",
  "cake",
  "calm",
  "camera",
  "camp",
  "canal",
  "cancel",
  "candy",
  "cannon",
  "canvas",
  "canyon",
  "capable",
  "capital",
  "captain",
  "capture",
  "car",
  "carbon",
  "card",
  "care",
  "career",
  "cargo",
  "carpet",
  "carrot",
  "carry",
  "cart",
  "carve",
  "case",
  "cash",
  "castle",
  "casual",
  "cat",
  "catch",
  "category",
  "cattle",
  "caught",
  "cause",
  "caution",
  "cave",
  "ceiling",
  "celebrate",
  "cell",
  "cement",
  "census",
  "century",
  "cereal",
  "chain",
  "chair",
  "chalk",
  "champion",
  "chance",
  "change",
  "channel",
  "chapter",
  "charge",
  "chase",
  "chat",
  "cheap",
  "check",
  "cheese",
  "chef",
  "cherry",
  "chest",
  "chicken",
  "chief",
  "child",
  "chimney",
  "choice",
  "choose",
  "chronic",
  "chunk",
  "church",
  "cinema",
  "circle",
  "citizen",
  "city",
  "civil",
  "claim",
  "clamp",
  "clarify",
  "class",
  "clay",
  "clean",
  "clear",
  "clerk",
  "clever",
  "click",
  "client",
  "cliff",
  "climb",
  "clock",
  "close",
  "cloth",
  "cloud",
  "clown",
  "club",
  "cluster",
  "coach",
  "coast",
  "coconut",
  "code",
  "coffee",
  "coil",
  "coin",
  "cold",
  "collar",
  "collect",
  "color",
  "column",
  "combine",
  "comfort",
  "comic",
  "common",
  "company",
  "compare",
  "compete",
  "complex",
  "compose",
  "concert",
  "concrete",
  "condition",
  "conduct",
  "confirm",
  "confuse",
  "connect",
  "consider",
  "consume",
  "contact",
  "contain",
  "content",
  "contest",
  "context",
  "control",
  "cook",
  "cool",
  "copper",
  "copy",
  "coral",
  "core",
  "corn",
  "corner",
  "correct",
  "cost",
  "cotton",
  "couch",
  "count",
  "country",
  "couple",
  "courage",
  "course",
  "cousin",
  "cover",
  "cow",
  "crack",
  "craft",
  "crane",
  "crash",
  "crawl",
  "cream",
  "create",
  "credit",
  "creek",
  "crew",
  "cricket",
  "crime",
  "crisp",
  "critic",
  "crop",
  "cross",
  "crowd",
  "crown",
  "cruel",
  "crush",
  "crystal",
  "cube",
  "culture",
  "cup",
  "curious",
  "current",
  "curtain",
  "curve",
  "cushion",
  "custom",
  "cute",
  "cycle",
  "dad",
  "daily",
  "damage",
  "dance",
  "danger",
  "daring",
  "dark",
  "dash",
  "daughter",
  "dawn",
  "day",
  "deal",
  "debate",
  "debt",
  "decade",
  "decide",
  "declare",
  "decline",
  "decorate",
  "decrease",
  "deer",
  "defeat",
  "defend",
  "define",
  "degree",
  "delay",
  "deliver",
  "demand",
  "denial",
  "dentist",
  "deny",
  "depart",
  "depend",
  "deposit",
  "depth",
  "deputy",
  "derive",
  "describe",
  "desert",
  "design",
  "desk",
  "despair",
  "destroy",
  "detail",
  "detect",
  "develop",
  "device",
  "devil",
  "diagram",
  "diamond",
  "diary",
  "dice",
  "diet",
  "differ",
  "digital",
  "dignity",
  "dilemma",
  "dinner",
  "dinosaur",
  "direct",
  "dirt",
  "discover",
  "discuss",
  "disease",
  "dish",
  "dismiss",
  "display",
  "distance",
  "divide",
  "divorce",
  "dizzy",
  "doctor",
  "document",
  "dog",
  "doll",
  "dolphin",
  "domain",
  "donate",
  "door",
  "double",
  "dough",
  "dove",
  "draft",
  "dragon",
  "drama",
  "draw",
  "dream",
  "dress",
  "drift",
  "drill",
  "drink",
  "drive",
  "drop",
  "drum",
  "dry",
  "duck",
  "dumb",
  "dune",
  "dust",
  "duty",
  "dwarf",
  "dynamic",
  "eager",
  "eagle",
  "early",
  "earn",
  "earth",
  "ease",
  "east",
  "echo",
  "ecology",
  "edge",
  "edit",
  "educate",
  "effort",
  "egg",
  "eight",
  "elbow",
  "elder",
  "electric",
  "elegant",
  "element",
  "elephant",
  "elevator",
  "elite",
  "email",
  "embody",
  "emerge",
  "emotion",
  "empty",
  "enable",
  "enact",
  "end",
  "enemy",
  "energy",
  "engage",
  "engine",
  "enjoy",
  "enlarge",
  "enter",
  "entire",
  "entry",
  "envelope",
  "episode",
  "equal",
  "equip",
  "era",
  "erase",
  "error",
  "escape",
  "essay",
  "essence",
  "estate",
  "eternal",
  "ethics",
  "evidence",
  "evil",
  "evoke",
  "exact",
  "example",
  "excess",
  "exchange",
  "excite",
  "exclude",
  "excuse",
  "execute",
  "exercise",
  "exhaust",
  "exhibit",
  "exist",
  "exit",
  "exotic",
  "expand",
  "expect",
  "explain",
  "explode",
  "explore",
  "express",
  "extend",
  "extra",
  "eye",
  "fabric",
  "face",
  "fact",
  "factor",
  "fade",
  "faint",
  "fair",
  "faith",
  "fall",
  "false",
  "fame",
  "family",
  "famous",
  "fan",
  "fancy",
  "fantasy",
  "farm",
  "fashion",
  "fast",
  "father",
  "fault",
  "favorite",
  "fear",
  "feature",
  "federal",
  "feed",
  "feel",
  "fence",
  "festival",
  "fever",
  "fiber",
  "fiction",
  "field",
  "fierce",
  "fight",
  "figure",
  "file",
  "fill",
  "film",
  "filter",
  "final",
  "finance",
  "find",
  "finger",
  "finish",
  "fire",
  "first",
  "fish",
  "fit",
  "five",
  "fix",
  "flag",
  "flame",
  "flash",
  "flat",
  "flavor",
  "flee",
  "flesh",
  "flight",
  "float",
  "flood",
  "floor",
  "flow",
  "flower",
  "fluid",
  "flush",
  "fly",
  "foam",
  "focus",
  "fog",
  "foil",
  "fold",
  "folk",
  "follow",
  "food",
  "foot",
  "force",
  "forest",
  "forget",
  "fork",
  "form",
  "fortune",
  "forward",
  "fossil",
  "foster",
  "found",
  "fountain",
  "fox",
  "frame",
  "free",
  "freeze",
  "fresh",
  "friend",
  "fringe",
  "frog",
  "front",
  "frost",
  "fruit",
  "fuel",
  "full",
  "fun",
  "funny",
  "fur",
  "furnace",
  "future",
  "gain",
  "galaxy",
  "gallery",
  "game",
  "gap",
  "garage",
  "garden",
  "garlic",
  "gas",
  "gate",
  "gather",
  "gauge",
  "gaze",
  "gear",
  "genius",
  "gentle",
  "genuine",
  "gesture",
  "ghost",
  "giant",
  "gift",
  "ginger",
  "giraffe",
  "girl",
  "give",
  "glad",
  "glass",
  "glide",
  "globe",
  "glory",
  "glove",
  "glow",
  "glue",
  "goat",
  "gold",
  "golf",
  "good",
  "goose",
  "gossip",
  "govern",
  "grab",
  "grace",
  "grade",
  "grain",
  "grand",
  "grape",
  "grass",
  "gravity",
  "great",
  "green",
  "grid",
  "grief",
  "grill",
  "grip",
  "ground",
  "group",
  "grow",
  "guard",
  "guess",
  "guest",
  "guide",
  "guilt",
  "guitar",
  "gun",
  "gym",
  "habit",
  "hair",
  "half",
  "hammer",
  "hand",
  "handle",
  "hang",
  "happy",
  "harbor",
  "hard",
  "harness",
  "harvest",
  "hat",
  "hate",
  "hawk",
  "hazard",
  "head",
  "health",
  "hear",
  "heart",
  "heat",
  "heavy",
  "hedge",
  "height",
  "hello",
  "helmet",
  "help",
  "hen",
  "hero",
  "hidden",
  "high",
  "hill",
  "hint",
  "hip",
  "hire",
  "history",
  "hit",
  "hobby",
  "hockey",
  "hold",
  "hole",
  "holiday",
  "home",
  "honey",
  "hood",
  "hope",
  "horn",
  "horror",
  "horse",
  "hospital",
  "host",
  "hotel",
  "hour",
  "house",
  "hover",
  "huge",
  "human",
  "humble",
  "humor",
  "hundred",
  "hungry",
  "hunt",
  "hurry",
  "hurt",
  "husband",
  "hybrid",
  "ice",
  "icon",
  "idea",
  "identify",
  "idle",
  "ignite",
  "ignore",
  "ill",
  "image",
  "imagine",
  "impact",
  "imply",
  "import",
  "impulse",
  "inch",
  "include",
  "income",
  "increase",
  "index",
  "indicate",
  "indoor",
  "industry",
  "infant",
  "infer",
  "inform",
  "inherit",
  "initial",
  "inject",
  "injury",
  "ink",
  "inner",
  "input",
  "insect",
  "inspire",
  "install",
  "instant",
  "instrument",
  "insult",
  "insurance",
  "intact",
  "integrate",
  "intense",
  "interest",
  "internal",
  "invent",
  "invest",
  "invite",
  "involve",
  "iron",
  "island",
  "isolate",
  "issue",
  "item",
  "ivory",
  "jacket",
  "jaguar",
  "jam",
  "jar",
  "jazz",
  "jeans",
  "jelly",
  "jewel",
  "job",
  "join",
  "joke",
  "journey",
  "joy",
  "judge",
  "juice",
  "jump",
  "jungle",
  "junior",
  "junk",
  "jury",
  "keen",
  "keep",
  "kettle",
  "key",
  "kick",
  "kid",
  "kind",
  "kingdom",
  "kiss",
  "kitchen",
  "kite",
  "knee",
  "knife",
  "knock",
  "knot",
  "know",
  "label",
  "labor",
  "ladder",
  "lady",
  "lake",
  "lamp",
  "land",
  "language",
  "large",
  "later",
  "laugh",
  "layer",
  "lazy",
  "lead",
  "leaf",
  "league",
  "lean",
  "leap",
  "learn",
  "leather",
  "leave",
  "lecture",
  "left",
  "legal",
  "legend",
  "leisure",
  "lemon",
  "lend",
  "length",
  "lens",
  "leopard",
  "lesson",
  "letter",
  "level",
  "library",
  "license",
  "life",
  "lift",
  "light",
  "limit",
  "line",
  "lion",
  "liquid",
  "list",
  "live",
  "lizard",
  "load",
  "loan",
  "local",
  "lock",
  "logic",
  "lonely",
  "long",
  "look",
  "loop",
  "loose",
  "lord",
  "loud",
  "love",
  "lower",
  "loyal",
  "luck",
  "luggage",
  "lumber",
  "lunar",
  "lunch",
  "lung",
  "machine",
  "mad",
  "magic",
  "magnet",
  "maid",
  "mail",
  "main",
  "major",
  "make",
  "mammal",
  "manage",
  "mango",
  "manner",
  "manual",
  "map",
  "marble",
  "march",
  "margin",
  "marine",
  "mark",
  "market",
  "marriage",
  "mask",
  "mass",
  "master",
  "match",
  "material",
  "matter",
  "maximum",
  "meadow",
  "mean",
  "measure",
  "meat",
  "mechanic",
  "medal",
  "media",
  "melody",
  "melt",
  "member",
  "memory",
  "mention",
  "menu",
  "mercy",
  "merge",
  "merit",
  "merry",
  "message",
  "metal",
  "method",
  "middle",
  "midnight",
  "mild",
  "mile",
  "milk",
  "mimic",
  "mind",
  "mineral",
  "minimum",
  "minor",
  "minute",
  "mirror",
  "misery",
  "miss",
  "mistake",
  "mix",
  "mobile",
  "model",
  "modify",
  "module",
  "moist",
  "molecule",
  "moment",
  "monitor",
  "monkey",
  "monster",
  "month",
  "moon",
  "moral",
  "morning",
  "mosaic",
  "mother",
  "motion",
  "motor",
  "mountain",
  "mouse",
  "mouth",
  "move",
  "movie",
  "mud",
  "muffin",
  "multiply",
  "muscle",
  "museum",
  "mushroom",
  "music",
  "mutual",
  "mystery",
  "myth",
  "nail",
  "naive",
  "name",
  "narrow",
  "nation",
  "nature",
  "navigate",
  "neck",
  "need",
  "negative",
  "neglect",
  "nerve",
  "nest",
  "net",
  "network",
  "neutral",
  "news",
  "nice",
  "night",
  "noble",
  "noise",
  "normal",
  "north",
  "nose",
  "note",
  "notice",
  "novel",
  "nuclear",
  "number",
  "nurse",
  "nut",
  "oak",
  "oath",
  "object",
  "observe",
  "obtain",
  "ocean",
  "october",
  "odor",
  "offer",
  "office",
  "oil",
  "okay",
  "old",
  "olive",
  "olympic",
  "onion",
  "online",
  "open",
  "opera",
  "opinion",
  "oppose",
  "option",
  "orange",
  "orbit",
  "order",
  "ordinary",
  "organ",
  "original",
  "outdoor",
  "outer",
  "output",
  "oven",
  "oxygen",
  "ozone",
  "pact",
  "page",
  "paint",
  "pair",
  "palace",
  "palm",
  "panda",
  "panel",
  "panic",
  "paper",
  "parade",
  "parent",
  "park",
  "parrot",
  "part",
  "party",
  "pass",
  "patch",
  "path",
  "patient",
  "patrol",
  "pattern",
  "pause",
  "pave",
  "payment",
  "peace",
  "peanut",
  "pear",
  "pebble",
  "pelican",
  "pencil",
  "people",
  "pepper",
  "perfect",
  "perform",
  "period",
  "permit",
  "person",
  "pet",
  "phone",
  "photo",
  "phrase",
  "physical",
  "piano",
  "pick",
  "picture",
  "piece",
  "pig",
  "pigeon",
  "pill",
  "pilot",
  "pin",
  "pink",
  "pioneer",
  "pipe",
  "pistol",
  "pitch",
  "pizza",
  "place",
  "planet",
  "plastic",
  "plate",
  "play",
  "please",
  "pledge",
  "pluck",
  "plug",
  "plunge",
  "pocket",
  "poem",
  "poet",
  "point",
  "polar",
  "pole",
  "police",
  "policy",
  "polish",
  "polite",
  "pond",
  "pool",
  "popular",
  "portion",
  "position",
  "possible",
  "post",
  "potato",
  "powder",
  "power",
  "practice",
  "praise",
  "predict",
  "prefer",
  "prepare",
  "present",
  "price",
  "pride",
  "primary",
  "print",
  "prison",
  "private",
  "prize",
  "problem",
  "process",
  "produce",
  "profit",
  "program",
  "project",
  "promise",
  "promote",
  "proof",
  "property",
  "protect",
  "proud",
  "prove",
  "provide",
  "public",
  "pull",
  "pulse",
  "pumpkin",
  "punch",
  "pupil",
  "pure",
  "purpose",
  "purse",
  "push",
  "puzzle",
  "pyramid",
  "quality",
  "quarter",
  "queen",
  "question",
  "quick",
  "quiet",
  "quiz",
  "quote",
  "rabbit",
  "raccoon",
  "radar",
  "radio",
  "rail",
  "rain",
  "raise",
  "random",
  "range",
  "rapid",
  "rare",
  "rate",
  "raven",
  "raw",
  "razor",
  "reach",
  "react",
  "read",
  "ready",
  "real",
  "reason",
  "rebel",
  "receive",
  "recipe",
  "record",
  "recycle",
  "reduce",
  "reflect",
  "reform",
  "refuse",
  "region",
  "regular",
  "reject",
  "relax",
  "release",
  "relief",
  "rely",
  "remain",
  "remember",
  "remind",
  "remote",
  "remove",
  "render",
  "renew",
  "rent",
  "repair",
  "repeat",
  "replace",
  "report",
  "rescue",
  "resemble",
  "reserve",
  "resist",
  "resource",
  "respect",
  "respond",
  "rest",
  "result",
  "retire",
  "return",
  "reveal",
  "review",
  "reward",
  "rhythm",
  "rib",
  "rice",
  "rich",
  "ride",
  "ridge",
  "rifle",
  "right",
  "rigid",
  "ring",
  "riot",
  "ripple",
  "risk",
  "ritual",
  "river",
  "road",
  "roast",
  "robot",
  "robust",
  "rocket",
  "rod",
  "rogue",
  "roll",
  "roof",
  "room",
  "root",
  "rope",
  "rose",
  "rotate",
  "rough",
  "round",
  "route",
  "royal",
  "rubber",
  "rude",
  "rug",
  "rule",
  "run",
  "rural",
  "rush",
  "rust",
  "sad",
  "saddle",
  "safe",
  "sail",
  "salad",
  "salmon",
  "salt",
  "sand",
  "sandwich",
  "satellite",
  "sauce",
  "sausage",
  "save",
  "scale",
  "scan",
  "scare",
  "scatter",
  "scene",
  "scheme",
  "school",
  "science",
  "scissors",
  "scout",
  "scrap",
  "screen",
  "script",
  "scrub",
  "sea",
  "seal",
  "search",
  "season",
  "seat",
  "second",
  "secret",
  "section",
  "secure",
  "seed",
  "seek",
  "segment",
  "select",
  "sell",
  "seminar",
  "senior",
  "sense",
  "sentence",
  "series",
  "serious",
  "service",
  "session",
  "settle",
  "seven",
  "shadow",
  "shaft",
  "shallow",
  "shape",
  "share",
  "shark",
  "sharp",
  "shed",
  "sheep",
  "sheet",
  "shelf",
  "shell",
  "shield",
  "shift",
  "shine",
  "ship",
  "shirt",
  "shock",
  "shoe",
  "shoot",
  "shop",
  "short",
  "shoulder",
  "shout",
  "show",
  "shrink",
  "shy",
  "sick",
  "side",
  "siege",
  "sight",
  "sign",
  "silent",
  "silk",
  "silly",
  "silver",
  "simple",
  "sing",
  "sink",
  "sister",
  "situate",
  "six",
  "size",
  "sketch",
  "ski",
  "skill",
  "skin",
  "skirt",
  "skull",
  "sky",
  "slam",
  "sleep",
  "slice",
  "slide",
  "slim",
  "slip",
  "slow",
  "slug",
  "small",
  "smart",
  "smell",
  "smile",
  "smoke",
  "smooth",
  "snake",
  "snap",
  "snow",
  "soap",
  "soccer",
  "social",
  "sock",
  "soda",
  "soft",
  "solar",
  "soldier",
  "solid",
  "solve",
  "song",
  "sorry",
  "sort",
  "soul",
  "sound",
  "soup",
  "source",
  "south",
  "space",
  "spare",
  "spark",
  "speak",
  "special",
  "speed",
  "spell",
  "spend",
  "sphere",
  "spice",
  "spider",
  "spike",
  "spin",
  "spirit",
  "split",
  "spoil",
  "spoon",
  "sport",
  "spot",
  "spray",
  "spread",
  "spring",
  "square",
  "squeeze",
  "squirrel",
  "stable",
  "stack",
  "stadium",
  "staff",
  "stage",
  "stairs",
  "stamp",
  "stand",
  "star",
  "start",
  "state",
  "station",
  "stay",
  "steak",
  "steam",
  "steel",
  "stem",
  "step",
  "stereo",
  "stick",
  "sting",
  "stock",
  "stomach",
  "stone",
  "stool",
  "stop",
  "store",
  "storm",
  "story",
  "stove",
  "straight",
  "strange",
  "strategy",
  "street",
  "stretch",
  "strike",
  "string",
  "strip",
  "strong",
  "student",
  "studio",
  "study",
  "stuff",
  "stumble",
  "style",
  "subject",
  "submit",
  "subway",
  "success",
  "sugar",
  "suggest",
  "suit",
  "summer",
  "sun",
  "sunny",
  "super",
  "supply",
  "support",
  "surface",
  "surprise",
  "surround",
  "survey",
  "swallow",
  "swamp",
  "swap",
  "swarm",
  "sweet",
  "swift",
  "swim",
  "swing",
  "switch",
  "sword",
  "symbol",
  "syrup",
  "system",
  "table",
  "tackle",
  "tag",
  "tail",
  "talent",
  "talk",
  "tall",
  "tank",
  "tape",
  "target",
  "taste",
  "tattoo",
  "taxi",
  "teach",
  "team",
  "tear",
  "tell",
  "temper",
  "temple",
  "tenant",
  "tennis",
  "tent",
  "term",
  "test",
  "text",
  "thank",
  "theory",
  "thick",
  "thief",
  "thigh",
  "thing",
  "think",
  "third",
  "thirsty",
  "thought",
  "thread",
  "threat",
  "three",
  "thrive",
  "throw",
  "thumb",
  "thunder",
  "ticket",
  "tide",
  "tiger",
  "tight",
  "timber",
  "time",
  "tiny",
  "tip",
  "tired",
  "title",
  "toast",
  "today",
  "toe",
  "token",
  "tomato",
  "tone",
  "tongue",
  "tool",
  "tooth",
  "top",
  "topic",
  "torch",
  "tornado",
  "tortoise",
  "total",
  "touch",
  "tough",
  "tourist",
  "tower",
  "town",
  "toy",
  "track",
  "trade",
  "traffic",
  "trail",
  "train",
  "trait",
  "trap",
  "trash",
  "travel",
  "tray",
  "treat",
  "tree",
  "trend",
  "trial",
  "tribe",
  "trick",
  "trigger",
  "trim",
  "trip",
  "trophy",
  "trouble",
  "truck",
  "true",
  "trumpet",
  "trust",
  "truth",
  "try",
  "tube",
  "tumble",
  "tunnel",
  "turkey",
  "turn",
  "turtle",
  "twelve",
  "twin",
  "twist",
  "type",
  "typical",
  "ugly",
  "umbrella",
  "uncle",
  "undo",
  "unfair",
  "unfold",
  "uniform",
  "unique",
  "universe",
  "unknown",
  "unlock",
  "unusual",
  "upgrade",
  "upper",
  "upset",
  "urban",
  "urge",
  "usage",
  "use",
  "usual",
  "utility",
  "vacant",
  "vacuum",
  "vague",
  "valid",
  "valley",
  "value",
  "van",
  "vapor",
  "vault",
  "vector",
  "vehicle",
  "velvet",
  "vendor",
  "venture",
  "verb",
  "version",
  "vessel",
  "veteran",
  "viable",
  "vibrant",
  "vice",
  "victory",
  "video",
  "view",
  "village",
  "vintage",
  "violin",
  "virus",
  "visit",
  "visual",
  "vital",
  "vivid",
  "vocal",
  "voice",
  "void",
  "volcano",
  "volume",
  "vote",
  "voyage",
  "wage",
  "wagon",
  "wait",
  "walk",
  "wall",
  "walnut",
  "wander",
  "want",
  "warm",
  "warn",
  "wash",
  "waste",
  "watch",
  "water",
  "wave",
  "wax",
  "wealth",
  "weapon",
  "wear",
  "weather",
  "weave",
  "web",
  "wedding",
  "wedge",
  "week",
  "weight",
  "weird",
  "welcome",
  "west",
  "wet",
  "whale",
  "wheat",
  "wheel",
  "whip",
  "whisper",
  "wide",
  "width",
  "wife",
  "wild",
  "wind",
  "window",
  "wine",
  "wing",
  "winter",
  "wire",
  "wisdom",
  "wise",
  "wish",
  "witness",
  "wolf",
  "woman",
  "wonder",
  "wood",
  "wool",
  "word",
  "work",
  "world",
  "worry",
  "worth",
  "wrap",
  "wreck",
  "wrist",
  "write",
  "wrong",
  "yard",
  "yarn",
  "year",
  "yellow",
  "young",
  "youth",
  "zebra",
  "zone",
  "zoo"
];
