// ============================================================
//  Manually-authored extra word lists.
//  Kept separate from data.js (which is auto-generated) so these
//  survive a regenerate. Merged into the category list at runtime.
//  Shape matches headsUpCategories: { name, emoji, primary, secondary, words }
// ============================================================
export const extraCategories = [
  {
    name: 'Sports',
    emoji: '🏀',
    primary: '#FF6F00',
    secondary: '#E65100',
    words: [
      'Basketball', 'Soccer', 'Football', 'Baseball', 'Tennis', 'Golf', 'Hockey',
      'Volleyball', 'Cricket', 'Rugby', 'Boxing', 'Wrestling', 'Swimming', 'Surfing',
      'Skiing', 'Snowboarding', 'Skateboarding', 'Cycling', 'Running', 'Marathon',
      'Gymnastics', 'Figure Skating', 'Bowling', 'Archery', 'Fencing', 'Karate',
      'Judo', 'Badminton', 'Table Tennis', 'Rowing', 'Sailing', 'Climbing',
      'Diving', 'Water Polo', 'Lacrosse', 'Polo', 'Curling', 'Darts', 'Pool',
      'Ultimate Frisbee', 'Dodgeball', 'Kickball', 'Pickleball', 'Handball',
    ],
  },
  {
    name: 'Countries',
    emoji: '🌍',
    primary: '#1976D2',
    secondary: '#0D47A1',
    words: [
      'United States', 'Canada', 'Mexico', 'Brazil', 'Argentina', 'United Kingdom',
      'France', 'Germany', 'Spain', 'Italy', 'Portugal', 'Netherlands', 'Belgium',
      'Switzerland', 'Sweden', 'Norway', 'Finland', 'Denmark', 'Iceland', 'Ireland',
      'Poland', 'Greece', 'Turkey', 'Russia', 'Ukraine', 'Egypt', 'Morocco',
      'Nigeria', 'Kenya', 'South Africa', 'India', 'China', 'Japan', 'South Korea',
      'Thailand', 'Vietnam', 'Indonesia', 'Philippines', 'Australia', 'New Zealand',
      'Saudi Arabia', 'Israel', 'Iran', 'Iraq', 'Chile', 'Peru', 'Colombia', 'Cuba',
    ],
  },
  {
    name: 'Superheroes',
    emoji: '🦸',
    primary: '#C62828',
    secondary: '#8E0000',
    words: [
      'Superman', 'Batman', 'Spider-Man', 'Iron Man', 'Captain America', 'Thor',
      'Hulk', 'Black Widow', 'Wonder Woman', 'The Flash', 'Aquaman', 'Green Lantern',
      'Wolverine', 'Deadpool', 'Black Panther', 'Doctor Strange', 'Scarlet Witch',
      'Captain Marvel', 'Ant-Man', 'Hawkeye', 'Star-Lord', 'Groot', 'Rocket Raccoon',
      'Cyclops', 'Storm', 'Jean Grey', 'Professor X', 'Magneto', 'Green Arrow',
      'Nightwing', 'Robin', 'Catwoman', 'Daredevil', 'The Punisher', 'Venom',
      'Joker', 'Thanos', 'Loki', 'Vision', 'Falcon', 'Winter Soldier',
    ],
  },
  {
    name: 'Disney',
    emoji: '🏰',
    primary: '#0277BD',
    secondary: '#01579B',
    words: [
      'Mickey Mouse', 'Minnie Mouse', 'Donald Duck', 'Goofy', 'Pluto', 'Cinderella',
      'Snow White', 'Sleeping Beauty', 'Ariel', 'Belle', 'Jasmine', 'Aladdin',
      'Mulan', 'Pocahontas', 'Tiana', 'Rapunzel', 'Elsa', 'Anna', 'Olaf', 'Moana',
      'Maui', 'Simba', 'Mufasa', 'Scar', 'Timon', 'Pumbaa', 'Peter Pan',
      'Tinker Bell', 'Captain Hook', 'Winnie the Pooh', 'Tigger', 'Eeyore',
      'Dumbo', 'Bambi', 'Pinocchio', 'Stitch', 'Buzz Lightyear', 'Woody',
      'Mike Wazowski', 'Sully', 'Nemo', 'Dory', 'Wall-E', 'Baymax',
    ],
  },
  {
    name: 'Emotions',
    emoji: '😊',
    primary: '#FBC02D',
    secondary: '#F57F17',
    words: [
      'Happy', 'Sad', 'Angry', 'Excited', 'Nervous', 'Scared', 'Surprised',
      'Confused', 'Bored', 'Tired', 'Jealous', 'Proud', 'Embarrassed', 'Shy',
      'Curious', 'Grateful', 'Hopeful', 'Lonely', 'Frustrated', 'Disgusted',
      'Calm', 'Anxious', 'Joyful', 'Disappointed', 'Annoyed', 'Relieved',
      'Guilty', 'Hungry', 'Sleepy', 'Silly', 'Brave', 'Worried', 'Content',
      'Overwhelmed', 'Amazed', 'Heartbroken', 'Determined', 'Suspicious',
    ],
  },
  {
    name: 'Fruits & Veggies',
    emoji: '🍓',
    primary: '#43A047',
    secondary: '#1B5E20',
    words: [
      'Apple', 'Banana', 'Orange', 'Strawberry', 'Blueberry', 'Raspberry',
      'Grape', 'Watermelon', 'Pineapple', 'Mango', 'Peach', 'Pear', 'Cherry',
      'Kiwi', 'Lemon', 'Lime', 'Coconut', 'Avocado', 'Pomegranate', 'Papaya',
      'Carrot', 'Broccoli', 'Cauliflower', 'Spinach', 'Lettuce', 'Cucumber',
      'Tomato', 'Potato', 'Onion', 'Garlic', 'Pepper', 'Corn', 'Peas',
      'Mushroom', 'Eggplant', 'Zucchini', 'Pumpkin', 'Celery', 'Cabbage',
      'Asparagus', 'Beet', 'Radish', 'Sweet Potato',
    ],
  },
  {
    name: 'Space',
    emoji: '🚀',
    primary: '#311B92',
    secondary: '#1A237E',
    words: [
      'Sun', 'Moon', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Venus', 'Mercury',
      'Neptune', 'Uranus', 'Pluto', 'Star', 'Galaxy', 'Black Hole', 'Comet',
      'Asteroid', 'Meteor', 'Nebula', 'Constellation', 'Milky Way', 'Solar System',
      'Astronaut', 'Rocket', 'Spaceship', 'Space Station', 'Satellite', 'Telescope',
      'Alien', 'UFO', 'Gravity', 'Orbit', 'Eclipse', 'Supernova', 'Big Bang',
      'Rover', 'Spacesuit', 'Launch Pad', 'Crater', 'Solar Flare',
    ],
  },
  {
    name: 'Mythical Creatures',
    emoji: '🐉',
    primary: '#6A1B9A',
    secondary: '#4A148C',
    words: [
      'Dragon', 'Unicorn', 'Phoenix', 'Griffin', 'Mermaid', 'Centaur', 'Minotaur',
      'Cyclops', 'Medusa', 'Pegasus', 'Werewolf', 'Vampire', 'Zombie', 'Ghost',
      'Goblin', 'Troll', 'Ogre', 'Elf', 'Fairy', 'Gnome', 'Dwarf', 'Giant',
      'Kraken', 'Loch Ness Monster', 'Bigfoot', 'Yeti', 'Chimera', 'Hydra',
      'Basilisk', 'Sphinx', 'Banshee', 'Leprechaun', 'Genie', 'Witch', 'Wizard',
      'Cerberus', 'Gorgon', 'Manticore',
    ],
  },
  {
    name: 'Vehicles',
    emoji: '🚗',
    primary: '#455A64',
    secondary: '#263238',
    words: [
      'Car', 'Truck', 'Motorcycle', 'Bicycle', 'Scooter', 'Bus', 'Train',
      'Subway', 'Tram', 'Airplane', 'Helicopter', 'Jet', 'Rocket', 'Boat',
      'Ship', 'Submarine', 'Canoe', 'Kayak', 'Jet Ski', 'Sailboat', 'Ferry',
      'Ambulance', 'Fire Truck', 'Police Car', 'Taxi', 'Limo', 'Van',
      'Pickup Truck', 'Tractor', 'Bulldozer', 'Crane', 'Forklift', 'Tank',
      'Golf Cart', 'Segway', 'Hot Air Balloon', 'Blimp', 'Hovercraft', 'Sled',
    ],
  },
  {
    name: 'Holidays',
    emoji: '🎉',
    primary: '#D81B60',
    secondary: '#880E4F',
    words: [
      'Christmas', 'Halloween', 'Thanksgiving', 'New Year', "Valentine's Day",
      'Easter', "St. Patrick's Day", "April Fools' Day", 'Independence Day',
      'Labor Day', 'Memorial Day', 'Mardi Gras', 'Cinco de Mayo', 'Hanukkah',
      'Diwali', 'Lunar New Year', 'Ramadan', 'Eid', 'Day of the Dead',
      "Mother's Day", "Father's Day", 'Birthday', 'Anniversary', 'Graduation',
      'Wedding', 'Black Friday', 'Cyber Monday', 'Earth Day', 'Pi Day',
      'Boxing Day', 'Groundhog Day',
    ],
  },
];
